name: Lint and Check Formatting
on:
  pull_request:
    branches:
      - "*"
    paths:
      - "pages/**"
      - "scripts/**"
      - "src/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn eslint --max-warnings 0 .
      - name: Check Formatting
        run: yarn prettier -c .
