name: Lint and Test (Data)
on:
  pull_request:
    paths:
      - "assets/**"
      - "src/scripts/utils/data-assets/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Check formatting
        run: yarn prettier -c assets
      - name: Run tests
        run: yarn test:data
