name: Lint and Test
on:
  pull_request:
    paths:
      - "pages/**"
      - "src/**"
      - "assets/**"
      - "yarn.lock"
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Lint
        run: yarn eslint --max-warnings 0 .

  format:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Check Formatting
        run: yarn prettier -c .

  types:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Build SVG Components
        run: node src/svgo/build.mjs
      - name: Check Types
        run: yarn test:types

  test:
    runs-on: ubuntu-latest
    needs: types
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Date
        run: echo "date=$(/bin/data -u "+%Y%m%d")" >> $GITHUB_ENV
      - name: AtlasAcademy API Cache
        id: atlas-cache
        uses: actions/cache@v3
        with:
          path: ".next/cache/atlasacademy"
          key: atlas-cache-${{ env.date }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      # Build Scripts step not yet needed, currently using tsm as a workaround
      #- name: Build Scripts
      #  run: yarn build:scripts
      - name: Run Legacy Tests
        run: yarn test:legacy
      - name: Run Code Tests
        run: yarn test:code
      - name: Run Data Tests
        run: yarn test:data --all
