name: Lint and Test
on:
  pull_request:
    paths:
      - "pages/**"
      - "src/**"
      - "assets/**"
      - "yarn.lock"
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Lint
        run: yarn eslint --max-warnings 0 .

  format:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Check Formatting
        run: yarn prettier -c .

  types:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Check Types
        run: yarn test:types

  test:
    runs-on: ubuntu-latest
    needs: types
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            server:
              - 'src/server/**'
            scripts:
              - 'src/scripts/**'
            assets:
              - 'assets/**'
      - name: AtlasAcademy API Cache
        id: atlas-cache
        uses: actions/cache@v3
        with:
          path: ".next/cache/atlasacademy"
          key: atlas-cache
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Test Server Modules
        if: steps.changes.outputs.server == 'true'
        run: yarn test:server
      - name: Test Scripts
        if: steps.changes.outputs.scripts == 'true'
        run: yarn test:scripts
      - name: Test Data
        if: steps.changes.outputs.assets == 'true'
        run: yarn test:data --all
