name: Update Browserslist Database
on:
  schedule:
    - cron: "0 0 1 */2 *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install dependencies
        run: yarn install --ignore-scripts
      - name: Update browserslist
        run: yarn browserslist --update-db
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Browserslist Database"
          branch: main
