name: update-upgrades-data
on:
  schedule:
    - cron: "10 8 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Run update script
        run: yarn upgrades:legacy
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Upgrades Data"
          branch: main
