name: Upgrade Project Dependencies
on:
  schedule:
    - cron: "0 0 1 */2 *"
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Update browserslist
        run: yarn browserslist --update-db
      - name: Update Spacetime
        run: yarn upgrade spacetime
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Dependencies"
          branch: main
