name: Check Formatting and Lint
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn install
          useRollingCache: true
      - name: Check Formatting
        run: yarn format:check
      - name: Lint
        run: yarn lint:strict
